# Generated by Django 5.1.1 on 2024-09-17 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок документа', max_length=255)),
                ('document_type', models.CharField(help_text='Тип документа (учебный план, отчет, и т. д.)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания документа')),
                ('updated_at', models.DateField(auto_now_add=True, help_text='Дата последнего обновления документа')),
                ('file', models.FileField(help_text='Файйл документа', upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(help_text='Номер версии документа')),
                ('file', models.FileField(help_text='Файл версии документа', upload_to='documents_version/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания версии')),
                ('document', models.ForeignKey(help_text='Документ для версии', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
        ),
    ]
